# This workflow builds, tests and releases an Picroft Stable binary image for Raspberry Pi

name: 'build: picroft github release'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build binary images
  build:
    name: build picroft github release
    runs-on: ubuntu-latest
    # Skip build if the commit message includes the string '[skip ci]'
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Get the version (git tag)
        id: get_version
        run: |
          echo ${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Install pi-gen required dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update --fix-missing
          sudo apt-get install -y coreutils quilt parted debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc jq
          sudo apt-get install -y qemu-user-static qemu-utils
      # Checkout the latest pi-gen repo code
      - name: Checkout the latest release pi-gen repo code
        run: |
          git clone https://github.com/RPi-Distro/pi-gen.git
          pushd pi-gen
          pwd
          ls -al
          popd

      # Copy picroft image build config to pi-gen working dir
      - name: Copy picroft image build config to pi-gen working dir
        run: cp ./config ./pi-gen/config

      # Copy picroft stage script to pi-gen working dir
      - name: Copy picroft stage script to pi-gen working dir
        run: |
          find ./pi-gen-stage-picroft -name "*.sh" -exec chmod +x {} \;
          cp -R ./pi-gen-stage-picroft ./pi-gen/
          ls -al ./pi-gen

      # Mark stage2 image to be skipped for faster build
      - name: Skip stage2 image - Standard Raspbian OS Lite
        run: |
          touch ./pi-gen/stage2/SKIP_IMAGES

      - name: Get mycroft-core latest release
        run: echo "BRANCH=`curl -sL https://api.github.com/repos/MycroftAI/mycroft-core/releases/latest | jq -r '.tag_name'`" >> $GITHUB_ENV

      # Run pi-gen image build script
      - name: Build picroft stable
        env:
          CI: true
        run: |
          pwd
          ls -al
          pushd pi-gen
          pwd
          git checkout tags/2021-10-30-raspios-bullseye
          sed -i 's/image_//g' ./build.sh
          ls -al
          sudo -E CLEAN=1 IMG_NAME=picroft-stable-`echo ${{ env.BRANCH }} | sed 's/release\///g'` ./build.sh -c config
          popd

      - name: Check prepared images
        run: |
          ls -al ./pi-gen/deploy

      - name: Build picroft nightly
        env:
          CI: true
          BRANCH: dev
        run: |
          pwd
          ls -al
          pushd pi-gen
          pwd
          ls -al
          sudo -E CLEAN=1 IMG_NAME=picroft-nightly-${{ env.BRANCH }} ./build.sh -c config
          popd

      - name: Check prepared images
        run: |
          ls -al ./pi-gen/deploy

      - name: Zipped image checksum
        run: sha256sum ./pi-gen/deploy/*.zip     

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Test build ${{ env.SHORT_SHA }}"
          files: |
            ./pi-gen/deploy/*.zip